services:
  mysql:
    image: mysql:8.0
    container_name: garden-watch-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: garden_watch
    ports:
      - "3306:3306"
    command:
      [
        "--bind-address=0.0.0.0",
        "--default-authentication-plugin=mysql_native_password"
      ]
    networks:
      - garden-net

networks:
  garden-net:
